project:
  type: website
  output-dir: docs
  preview:
    port: 4444

website:
  title: "Exploring Philadelphia's Amenity Landscape"
  site-url: "https://luckylaharltim.github.io/MUSA_5500_Final/" 
  repo-url: https://github.com/LuckyLaharlTim/MUSA_5500_Final.git 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Anna Duan, Trevor Kapuvari, & Timothy Oliver, 2023"

  sidebar:
    logo: "images/dancing icon.png"
    pinned: true
    align: center
<<<<<<< HEAD
    

=======
    tools: 
      - icon: github
        href: https://github.com/LuckyLaharlTim/MUSA_5500_Final
        text: "Source GitHub"
      - icon: github
        href: https://github.com/annaduan09
        text: "Anna Duan Github Profile" 
      - icon: github
        href: https://github.com/TrevorKap
        text: "Trevor Kapuvari Github Profile" 
      - icon: github
        href: https://github.com/LuckyLaharlTim
        text: "Timothy Oliver Github Profile" 
      - icon: linkedin
        href: https://www.linkedin.com/in/trevor-kapuvari-a25876253/
        text: "Trevor Kapuvari LinkedIn"

      - icon: linkedin
        href: https://www.linkedin.com/in/timoliver200?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BM4Ej%2F58xQdy7qwIFEM3FFw%3D%3D
        text: "Some Linked In" 

style: "docked"
search: true
collapse-level: 2
contents:
  - href: index.qmd
    text: Welcome
  - about.qmd
  - section: contact/index.qmd
    contents:
      - contact/references.qmd
      - contact/acknowledgements.qmd
  - section: analysis/index.qmd
    contents:
      - analysis/methods.qmd
      - analysis/pull_businesses.Rmd
      - data_prep.ipynb
      - exploratory.ipynb
>>>>>>> dacdcfcb6aae4e7553b4534a41977f1dc0c68e94

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/methods.qmd
          - data_prep.ipynb
          - exploratory.ipynb
      - section: contact/index.qmd
        contents:
          - contact/acknowledgements.qmd
          
format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
