project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Finding Commercial Corridors in Philadelphia"
  site-url: "https://luckylaharltim.github.io/MUSA_5500_Final/" 
  repo-url: https://github.com/LuckyLaharlTim/MUSA_5500_Final.git 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Anna Duan, Trevor Kapuvari, & Timothy Oliver, 2023"

  sidebar:
    logo: "images/hip_logo.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/LuckyLaharlTim/MUSA_5500_Final
        text: "Analysis Project GitHub"
      - icon: github
        href: https://github.com/annaduan09
        text: "Anna Duan Github Profile" 
      - icon: github
        href: https://github.com/TrevorKap
        text: "Trevor Kapuvari Github Profile" 
      - icon: github
        href: https://github.com/LuckyLaharlTim
        text: "Timothy Oliver Github Profile" 
      - icon: linkedin
        href: https://www.linkedin.com/in/timoliver200?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BM4Ej%2F58xQdy7qwIFEM3FFw%3D%3D
        text: "Some Linked In" 


    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: contact/index.qmd
        contents:
          - contact/references.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/methods.qmd
          - analysis/5-yelp_clean_and_explore.ipynb
          - analysis/results.qmd

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




