project:
  type: website
  output-dir: docs
website:
  navbar:
    search: false
    pinned: true
    left:
      - href: index.qmd
        text: 'Home'
      - href: portfolio.qmd
        text: 'Work Samples'
      - href: resume.qmd
        text: 'About Me'
    right:
        - icon: linkedin
          href: www.linkedin.com/in/annaduan
        - icon: github
          href: https://github.com/annaduan09
        - icon: envelope
          href: mailto:annaduan@sas.upenn.edu

  page-footer:
    left: "&copy; cc-Anna Duan, 2024"
        
format:
  html:
    highlight-style: solarized
    theme: cosmo
