project:
  type: website
  output-dir: docs
  preview:
    port: 4444

website:
  title: "Exploring Philadelphia's Amenity Landscape"
  site-url: "https://luckylaharltim.github.io/MUSA_5500_Final/" 
  repo-url: https://github.com/LuckyLaharlTim/MUSA_5500_Final.git 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Anna Duan, Trevor Kapuvari, & Timothy Oliver, 2023"

  sidebar:
    logo: "images/dancing icon.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - section: about.qmd
        contents:
          - contact/index.qmd
          - contact/acknowledgements.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/methods.qmd
          - analysis/pull_businesses.Rmd
          - data/scraping_zillow_data.ipynb
          - analysis/data_prep.ipynb
          - analysis/exploratory.ipynb
          - analysis/text_analysis.ipynb
      - section: conclusion.qmd
          
format:
  html:
    highlight-style: solarized
    theme: flatly
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
