---
title: "Discussion: proposing neighborhood amenity clusters"
---


## Amenity Landscape  
- highest concentration of amenities is in center city
- amenity landscape dominated by restaurants, services, and retail

## Variation in amenities  
- not all amenity types are clustered in center city
- some are concentrated in specific areas (e.g. green space, sports, historic, arts)
- this makes Philadelphia an interesting city for amenity clusters
- beyond the amenity-dense center city, neighborhoods are highly specialized
- restaurants, beauty, and grocery, for example, are all over, while arts and histroic sites are concentrated in specific districts

## Typologies  
In our analysis, we identified 7 distinct clusters of neighborhoods with similar amenity compositions. These clusters were determined using a k-means cluster analysis of the percentage share of each amenity type. Percentage share was used in lieu of raw counts or counts per area to counter the high variation in population density, and to emphasize qualitative differences rather than rank neighborhoods against each other. 

## Applications for research  

## Limitations   

Our analysis is firstly limited by a number of disparities between the demographics of Yelp’s user base and Philadelphia’s residents. First, Yelp users skew older, with 40% of users over 55 years of age, 35% from 35 to 54, and only 25% from 18 to 34. Philadelphia’s median age is 34.6. In terms of income, Yelp users tend to be higher income. 80% of users make more than $60k per year. By contrast, according to the US Census Bureau, Philadelphia has a median income of $27,331. Finally, 77% of Yelp users hold at least a college degree, compared to 33.6% of Philadelphians. Combined, these disparities suggest that the businesses listed and most reviewed on Yelp do not fully portray the amenity landscape of Philadelphia.

Using Yelp data presents another challenge: when sorting business listings using the alias field, there appears to be no hierarchy of importance between the three terms in the alias. For instance, in some cases, the first term would be the most specific (e.g. pizza shop) and the third term would be less specific (e.g. food delivery). In other cases, it would be the reverse. Because of this, we had to write a complicated Python script for iterating over the three alias terms for each business and replacing the first term with the second or third when the first term is vague. In cases where all three terms were vague, we searched the business titles for terms suggesting specific restaurant types or cuisines (e.g. pizzeria for pizza, or steaks for sandwich shops). While this iterative process allows us to capture more meaning from our data, it is labor intensive and prone to human error and subjectivity, making it less replicable than simply identifying the first term in the alias field as the business’s subcategory. 

<a href="https://www.yelp-press.com/company/fast-facts/default.aspx">Yelp User Demographics</a>

The use of Zillow data benefits from problems in the Yelp data's current form such as searching no clear ranking in the terms under a business's alias, but ensuring that these terms do not overlap with information about a house in the description is difficult. 

Furthermore, the presence of records that put the address within the description or have no address at all present issues with offering later granularity should they not have their neighborhood in the description.

Otherwise, current failure to include geocoding or some weight or importance factor for ranking mentions--ideally giving great preference to specific business mentions--are the largest limitations of the Zillow analysis in our current implementation.

