---
title: "Default page is in index.qmd"
subtitle: "Showing What Philadelphia Neghborhoods Offer"
---

<!-- start the markdown section for writing -->
<!-- I recommend playing around in design with the index.qmd to make the story page Anna recommended. -->
## Welcome!

Philadelphia, like many cities has a wide diversity of neighborhoods each with their own unique atmosphere. As these neighborhoods and the lifestyles associated evolve, it is the responsibility of the city to monitor and record the community amenities that service residents and newcomers. Open-sources provide broad overviews but fail to measure the nuanced preferences of residents.
For instance, parks and greenspaces are valued differently in each neighborhood and vary in quality, yet OpenDataPhilly.org lists all parks managed by Parks and Recreation without the additional insight on quality and community feedback. 
Combining the pre-existing nuance between what is listed versus what is valued, exacterbated by  the pandemic, we have developed a tool that creates a comprehensive frame of each neighborhood in Philadelphia. Ultimately, this tool will serve as a way of uplifting neighborhoods by displaying their most valued assets and showcasing the lifestyle and features they have to offer. 



::: {.callout-important}
This template site, including the layout it uses, is just a suggested place to start! For your final project, you're welcome (and encouraged) to 
make as many changes as you like to best fit your project.
:::

## Find out more

The code for this repository is hosted on our course's GitHub page: [https://github.com/MUSA-550-Fall-2023/quarto-website-template](https://github.com/MUSA-550-Fall-2023/quarto-website-template).

We covered the basics of getting started with Quarto and GitHub Pages in week 9. Take a look at
[the slides for lecture 9A](https://musa-550-fall-2023.github.io/content/week-9/lecture-9A.html) to find out more.






 
