project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Finding Commercial Corridors in Philadelphia"
  site-url: "https://luckylaharltim.github.io/MUSA_5500_Final/" 
  repo-url: https://github.com/LuckyLaharlTim/MUSA_5500_Final.git 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Anna Duan, Trevor Kapuvari, & Timothy Oliver, 2023"

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.pha.phila.gov/housing/housing-choice-voucher/
        text: "Philadelphia Housing Authority - Housing Choice Vouchers"
      - icon: github
        href: https://github.com/LuckyLaharlTim/MUSA_5500_Final
        text: "Analysis Project GitHub"
      - icon: spotify
        href: https://twitter.com/nicholashand
        text: "Other Social Media --CHANGE ICON AND LINK"         

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/1-python-code-blocks.qmd 
          - analysis/2-static-images.ipynb
          - analysis/3-altair-hvplot.ipynb
          - analysis/4-folium.ipynb
          # - analysis/5-yelp_explore.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




